### ISSUE TITLE
after using " compile 'com.github.oliveiradev:image-zoom:0.4.0'" instead of "compile 'com.github.oliveiradev:image-zoom:0.1.0'" while clicking on image this exception occurs

### ISSUE THREAD

**Issue by nilabja1312** [oliveiradev/image-zoom#6]
java.lang.ClassCastException: android.graphics.drawable.TransitionDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                                                                                at com.github.oliveiradev.image_zoom.lib.widget.ZoomAnimation.zoomImageFromThumb(ZoomAnimation.java:49)
                                                                                at com.github.oliveiradev.image_zoom.lib.widget.ZoomAnimation.zoom(ZoomAnimation.java:35)
                                                                                at com.github.oliveiradev.image_zoom.lib.widget.ImageZoom.performZoom(ImageZoom.java:106)
                                                                                at com.github.oliveiradev.image_zoom.lib.widget.ImageZoom.performClick(ImageZoom.java:99)
                                                                                at android.view.View$PerformClick.run(View.java:18473)
                                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by oliveiradev** [comment]
Hey @nilabja1312 , I will try simulate this scene, thanks for you report
